In [79]:
import numpy as np
import pandas as pd
import re
from datetime import datetime

In [3]:
presidents = pd.read_csv(r"D:/Introduction-to-Data-Science-in-Python/week-2/datasets/presidents.csv", index_col = 0)
presidents.head()

,President,Born,Age atstart of presidency,Age atend of presidency,Post-presidencytimespan,Died,Age
#,,,,,,,
1,George Washington,"Feb 22, 1732[a]","57 years, 67 daysApr 30, 1789","65 years, 10 daysMar 4, 1797","2 years, 285 days","Dec 14, 1799","67 years, 295 days"
2,John Adams,"Oct 30, 1735[a]","61 years, 125 daysMar 4, 1797","65 years, 125 daysMar 4, 1801","25 years, 122 days","Jul 4, 1826","90 years, 247 days"
3,Thomas Jefferson,"Apr 13, 1743[a]","57 years, 325 daysMar 4, 1801","65 years, 325 daysMar 4, 1809","17 years, 122 days","Jul 4, 1826","83 years, 82 days"
4,James Madison,"Mar 16, 1751[a]","57 years, 353 daysMar 4, 1809","65 years, 353 daysMar 4, 1817","19 years, 116 days","Jun 28, 1836","85 years, 104 days"
5,James Monroe,"Apr 28, 1758","58 years, 310 daysMar 4, 1817","66 years, 310 daysMar 4, 1825","6 years, 122 days","Jul 4, 1831","73 years, 67 days"

In [42]:
f_names = presidents.President.apply(lambda full_name: re.findall("[A-Z][\w]+[^\s]", full_name)[0])
f_names

#
1         George
2           John
3         Thomas
4          James
5          James
6           John
7         Andrew
8         Martin
9        William
10          John
11         James
12       Zachary
13       Millard
14      Franklin
15         James
16       Abraham
17        Andrew
18       Ulysses
19    Rutherford
20         James
21       Chester
22        Grover
23      Benjamin
24        Grover
25       William
26      Theodore
27       William
28       Woodrow
29        Warren
30        Calvin
31       Herbert
32      Franklin
33         Harry
34        Dwight
35          John
36        Lyndon
37       Richard
38        Gerald
39         Jimmy
40        Ronald
41        George
42          Bill
43        George
44        Barack
Name: President, dtype: object

In [46]:
l_names = presidents.President.apply(lambda full_name: re.findall("[^\s][A-Z,\.]*[\s]*[a-zA-Z]+", full_name)[1])
l_names

#
1        Washington
2             Adams
3         Jefferson
4           Madison
5            Monroe
6            Quincy
7           Jackson
8               Van
9       H. Harrison
10            Tyler
11          K. Polk
12           Taylor
13         Fillmore
14           Pierce
15         Buchanan
16          Lincoln
17          Johnson
18         S. Grant
19         B. Hayes
20      A. Garfield
21        A. Arthur
22        Cleveland
23         Harrison
24        Cleveland
25         McKinley
26        Roosevelt
27          H. Taft
28           Wilson
29       G. Harding
30         Coolidge
31           Hoover
32     D. Roosevelt
33        S. Truman
34    D. Eisenhower
35       F. Kennedy
36       B. Johnson
37            Nixon
38             Ford
39           Carter
40           Reagan
41             H. W
42          Clinton
43          W. Bush
44            Obama
Name: President, dtype: object

In [65]:
presidents.loc[:, "First_name"] = presidents.President.apply(lambda full_name: re.findall("^[A-Z][a-zA-Z]+[^\s]", full_name)[0])
presidents.First_name

#
1         George
2           John
3         Thomas
4          James
5          James
6           John
7         Andrew
8         Martin
9        William
10          John
11         James
12       Zachary
13       Millard
14      Franklin
15         James
16       Abraham
17        Andrew
18       Ulysses
19    Rutherford
20         James
21       Chester
22        Grover
23      Benjamin
24        Grover
25       William
26      Theodore
27       William
28       Woodrow
29        Warren
30        Calvin
31       Herbert
32      Franklin
33         Harry
34        Dwight
35          John
36        Lyndon
37       Richard
38        Gerald
39         Jimmy
40        Ronald
41        George
42          Bill
43        George
44        Barack
Name: First_name, dtype: object

In [68]:
presidents.loc[:, "Born"] = presidents.Born.apply(lambda dob: re.findall("^[A-Z]{1}[a-z]{2}\s[\d]+\,\s\d{4}", dob)[0])

In [70]:
presidents

,President,Born,Age atstart of presidency,Age atend of presidency,Post-presidencytimespan,Died,Age,First_name
#,,,,,,,,
1,George Washington,"Feb 22, 1732","57 years, 67 daysApr 30, 1789","65 years, 10 daysMar 4, 1797","2 years, 285 days","Dec 14, 1799","67 years, 295 days",George
2,John Adams,"Oct 30, 1735","61 years, 125 daysMar 4, 1797","65 years, 125 daysMar 4, 1801","25 years, 122 days","Jul 4, 1826","90 years, 247 days",John
3,Thomas Jefferson,"Apr 13, 1743","57 years, 325 daysMar 4, 1801","65 years, 325 daysMar 4, 1809","17 years, 122 days","Jul 4, 1826","83 years, 82 days",Thomas
4,James Madison,"Mar 16, 1751","57 years, 353 daysMar 4, 1809","65 years, 353 daysMar 4, 1817","19 years, 116 days","Jun 28, 1836","85 years, 104 days",James
5,James Monroe,"Apr 28, 1758","58 years, 310 daysMar 4, 1817","66 years, 310 daysMar 4, 1825","6 years, 122 days","Jul 4, 1831","73 years, 67 days",James
6,John Quincy Adams,"Jul 11, 1767","57 years, 236 daysMar 4, 1825","61 years, 236 daysMar 4, 1829","18 years, 356 days","Feb 23, 1848","80 years, 227 days",John
7,Andrew Jackson,"Mar 15, 1767","61 years, 354 daysMar 4, 1829","69 years, 354 daysMar 4, 1837","8 years, 96 days","Jun 8, 1845","78 years, 85 days",Andrew
8,Martin Van Buren,"Dec 5, 1782","54 years, 89 daysMar 4, 1837","58 years, 89 daysMar 4, 1841","21 years, 142 days","Jul 24, 1862","79 years, 231 days",Martin
9,William H. Harrison,"Feb 9, 1773","68 years, 23 daysMar 4, 1841","68 years, 54 days Apr 4, 1841[b]",NaN,"Apr 4, 1841","68 years, 54 days",William
10,John Tyler,"Mar 29, 1790","51 years, 6 daysApr 4, 1841","54 years, 340 daysMar 4, 1845","16 years, 320 days","Jan 18, 1862","71 years, 295 days",John
11,James K. Polk,"Nov 2, 1795","49 years, 122 daysMar 4, 1845","53 years, 122 daysMar 4, 1849",103 days,"Jun 15, 1849","53 years, 225 days",James
12,Zachary Taylor,"Nov 24, 1784","64 years, 100 daysMar 4, 1849","65 years, 227 daysJul 9, 1850[b]",NaN,"Jul 9, 1850","65 years, 227 days",Zachary
13,Millard Fillmore,"Jan 7, 1800","50 years, 183 daysJul 9, 1850","53 years, 56 daysMar 4, 1853","21 years, 4 days","Mar 8, 1874","74 years, 60 days",Millard
14,Franklin Pierce,"Nov 23, 1804","48 years, 101 daysMar 4, 1853","52 years, 101 daysMar 4, 1857","12 years, 218 days","Oct 8, 1869","64 years, 319 days",Franklin
15,James Buchanan,"Apr 23, 1791","65 years, 315 daysMar 4, 1857","69 years, 315 daysMar 4, 1861","7 years, 89 days","Jun 1, 1868","77 years, 39 days",James
16,Abraham Lincoln,"Feb 12, 1809","52 years, 20 daysMar 4, 1861","56 years, 62 daysApr 15, 1865[b]",NaN,"Apr 15, 1865","56 years, 62 days",Abraham
17,Andrew Johnson,"Dec 29, 1808","56 years, 107 daysApr 15, 1865","60 years, 65 daysMar 4, 1869","6 years, 149 days","Jul 31, 1875","66 years, 214 days",Andrew
18,Ulysses S. Grant,"Apr 27, 1822","46 years, 311 daysMar 4, 1869","54 years, 311 daysMar 4, 1877","8 years, 141 days","Jul 23, 1885","63 years, 87 days",Ulysses
19,Rutherford B. Hayes,"Oct 4, 1822","54 years, 151 daysMar 4, 1877","58 years, 151 daysMar 4, 1881","11 years, 319 days","Jan 17, 1893","70 years, 105 days",Rutherford
20,James A. Garfield,"Nov 19, 1831","49 years, 105 daysMar 4, 1881","49 years, 304 daysSep 19, 1881[b]",NaN,"Sep 19, 1881","49 years, 304 days",James
21,Chester A. Arthur,"Oct 5, 1829","51 years, 349 daysSep 19, 1881","55 years, 150 daysMar 4, 1885","1 year, 259 days","Nov 18, 1886","57 years, 44 days",Chester
22,Grover Cleveland,"Mar 18, 1837","47 years, 351 daysMar 4, 1885","51 years, 351 daysMar 4, 1889","4 years, 0 days[c]","Jun 24, 1908","71 years, 98 days",Grover
23,Benjamin Harrison,"Aug 20, 1833","55 years, 196 daysMar 4, 1889","59 years, 196 daysMar 4, 1893","8 years, 9 days","Mar 13, 1901","67 years, 205 days",Benjamin
24,Grover Cleveland,"Mar 18, 1837","55 years, 351 daysMar 4, 1893","59 years, 351 daysMar 4, 1897","11 years, 112 days[d]","Jun 24, 1908","71 years, 98 days",Grover
25,William McKinley,"Jan 29, 1843","54 years, 34 daysMar 4, 1897","58 years, 228 daysSep 14, 1901[b]",NaN,"Sep 14, 1901","58 years, 228 days",William
26,Theodore Roosevelt,"Oct 27, 1858","42 years, 322 daysSep 14, 1901","50 years, 128 daysMar 4, 1909","9 years, 308 days","Jan 6, 1919","60 years, 71 days",Theodore
27,William H. Taft,"Sep 15, 1857","51 years, 170 daysMar 4, 1909","55 years, 170 daysMar 4, 1913","17 years, 4 days","Mar 8, 1930","72 years, 174 days",William
28,Woodrow Wilson,"Dec 28, 1856","56 years, 66 daysMar 4, 1913","64 years, 66 daysMar 4, 1921","2 years, 336 days","Feb 3, 1924","67 years, 37 days",Woodrow
29,Warren G. Harding,"Nov 2, 1865","55 years, 122 daysMar 4, 1921","57 years, 273 daysAug 2, 1923[b]",NaN,"Aug 2, 1923","57 years, 273 days",Warren
30,Calvin Coolidge,"Jul 4, 1872","51 years, 29 daysAug 2, 1923","56 years, 243 daysMar 4, 1929","3 years, 307 days","Jan 5, 1933","60 years, 185 days",Calvin
31,Herbert Hoover,"Aug 10, 1874","54 years, 206 daysMar 4, 1929","58 years, 206 daysMar 4, 1933","31 years, 230 days","Oct 20, 1964","90 years, 71 days",Herbert
32,Franklin D. Roosevelt,"Jan 30, 1882","51 years, 33 daysMar 4, 1933","63 years, 72 daysApr 12, 1945[b]",NaN,"Apr 12, 1945","63 years, 72 days",Franklin
33,Harry S. Truman,"May 8, 1884","60 years, 339 daysApr 12, 1945","68 years, 257 daysJan 20, 1953","19 years, 341 days","Dec 26, 1972","88 years, 232 days",Harry
34,Dwight D. Eisenhower,"Oct 14, 1890","62 years, 98 daysJan 20, 1953","70 years, 98 daysJan 20, 1961","8 years, 67 days","Mar 28, 1969","78 years, 165 days",Dwight
35,John F. Kennedy,"May 29, 1917","43 years, 236 daysJan 20, 1961","46 years, 177 daysNov 22, 1963[b]",NaN,"Nov 22, 1963","46 years, 177 days",John
36,Lyndon B. Johnson,"Aug 27, 1908","55 years, 87 daysNov 22, 1963","60 years, 146 daysJan 20, 1969","4 years, 2 days","Jan 22, 1973","64 years, 148 days",Lyndon
37,Richard Nixon,"Jan 9, 1913","56 years, 11 daysJan 20, 1969","61 years, 212 daysAug 9, 1974[e]","19 years, 256 days","Apr 22, 1994","81 years, 103 days",Richard
38,Gerald Ford,"Jul 14, 1913","61 years, 26 daysAug 9, 1974","63 years, 190 daysJan 20, 1977","29 years, 340 days","Dec 26, 2006","93 years, 165 days",Gerald
39,Jimmy Carter,"Oct 1, 1924","52 years, 111 daysJan 20, 1977","56 years, 111 daysJan 20, 1981","38 years, 175 days",(living),"94 years, 286 days",Jimmy
40,Ronald Reagan,"Feb 6, 1911","69 years, 349 daysJan 20, 1981","77 years, 349 daysJan 20, 1989","15 years, 137 days","Jun 5, 2004","93 years, 120 days",Ronald
41,George H. W. Bush,"Jun 12, 1924","64 years, 222 daysJan 20, 1989","68 years, 222 daysJan 20, 1993","25 years, 314 days","Nov 30, 2018","94 years, 171 days",George
42,Bill Clinton,"Aug 19, 1946","46 years, 154 daysJan 20, 1993","54 years, 154 daysJan 20, 2001","18 years, 175 days",(living),"72 years, 329 days",Bill
43,George W. Bush,"Jul 6, 1946","54 years, 198 daysJan 20, 2001","62 years, 198 daysJan 20, 2009","10 years, 175 days",(living),"73 years, 8 days",George
44,Barack Obama,"Aug 4, 1961","47 years, 169 daysJan 20, 2009","55 years, 169 daysJan 20, 2017","2 years, 175 days",(living),"57 years, 344 days",Barack

In [90]:
pd.to_datetime(presidents.Born, format = "%b %d, %Y")

# list(map(lambda date_str: datetime.strptime(date_str, "%b %d, %Y"), presidents.Born))

#
1    1732-02-22
2    1735-10-30
3    1743-04-13
4    1751-03-16
5    1758-04-28
6    1767-07-11
7    1767-03-15
8    1782-12-05
9    1773-02-09
10   1790-03-29
11   1795-11-02
12   1784-11-24
13   1800-01-07
14   1804-11-23
15   1791-04-23
16   1809-02-12
17   1808-12-29
18   1822-04-27
19   1822-10-04
20   1831-11-19
21   1829-10-05
22   1837-03-18
23   1833-08-20
24   1837-03-18
25   1843-01-29
26   1858-10-27
27   1857-09-15
28   1856-12-28
29   1865-11-02
30   1872-07-04
31   1874-08-10
32   1882-01-30
33   1884-05-08
34   1890-10-14
35   1917-05-29
36   1908-08-27
37   1913-01-09
38   1913-07-14
39   1924-10-01
40   1911-02-06
41   1924-06-12
42   1946-08-19
43   1946-07-06
44   1961-08-04
Name: Born, dtype: datetime64[ns]