In [1]:
import pandas as pd
import numpy as np
from string import ascii_uppercase

In [2]:
census = pd.read_csv(r"D:/Introduction-to-Data-Science-in-Python/week-3/datasets/census.csv")
census.head()

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
0,40,3,6,1,0,Alabama,Alabama,4779736,4780127,4785161,...,0.002295,-0.193196,0.381066,0.582002,-0.467369,1.030015,0.826644,1.383282,1.724718,0.712594
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183193,...,14.832960,17.647293,21.845705,19.243287,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499
3,50,3,6,1,5,Alabama,Barbour County,27457,27457,27341,...,-4.728132,-2.500690,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299
4,50,3,6,1,7,Alabama,Bibb County,22915,22919,22861,...,-5.527043,-5.068871,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861

In [17]:
%%timeit -n 10

for state in census.STNAME.unique():
    np.mean(census.query("STNAME == @state").loc[:, "CENSUS2010POP"])

111 ms ± 5.49 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [7]:
groups = list()
splitted_DataFrames = list()

for (group, DataFrame) in census.groupby("STNAME"):
    groups.append(group)
    splitted_DataFrames.append(DataFrame)

In [13]:
print(*groups, sep = ", ")

Alabama, Alaska, Arizona, Arkansas, California, Colorado, Connecticut, Delaware, District of Columbia, Florida, Georgia, Hawaii, Idaho, Illinois, Indiana, Iowa, Kansas, Kentucky, Louisiana, Maine, Maryland, Massachusetts, Michigan, Minnesota, Mississippi, Missouri, Montana, Nebraska, Nevada, New Hampshire, New Jersey, New Mexico, New York, North Carolina, North Dakota, Ohio, Oklahoma, Oregon, Pennsylvania, Rhode Island, South Carolina, South Dakota, Tennessee, Texas, Utah, Vermont, Virginia, Washington, West Virginia, Wisconsin, Wyoming

In [15]:
len(groups)

51

In [16]:
splitted_DataFrames[0].head()

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
0,40,3,6,1,0,Alabama,Alabama,4779736,4780127,4785161,...,0.002295,-0.193196,0.381066,0.582002,-0.467369,1.030015,0.826644,1.383282,1.724718,0.712594
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183193,...,14.832960,17.647293,21.845705,19.243287,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499
3,50,3,6,1,5,Alabama,Barbour County,27457,27457,27341,...,-4.728132,-2.500690,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299
4,50,3,6,1,7,Alabama,Bibb County,22915,22919,22861,...,-5.527043,-5.068871,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861

In [18]:
%%timeit -n 10

for group, dataframe in census.groupby("STNAME"):
    np.mean(dataframe.loc[:, "CENSUS2010POP"])

6.14 ms ± 1.02 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [4]:
def categorizeByStateStartAlphabet(state_name: str) -> str:
    if state_name[0] in ascii_uppercase[:10]:
        return "Category One"
    elif state_name[0] in ascii_uppercase[10:20]:
        return "Category Two"
    elif state_name[0] in ascii_uppercase[20:]:
        return "Category Three"
    else:
        return None

In [27]:
_census = census.set_index("STNAME")

In [32]:
# group by would operate on index by default if a column name is not specified explicitly

for group, dataframe in _census.groupby(categorizeByStateStartAlphabet):
    # print(group)
    print("{}: States: {}".format(group, list(dataframe.index.unique())))

Category One: States: ['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut', 'Delaware', 'District of Columbia', 'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa']
Category Three: States: ['Utah', 'Vermont', 'Virginia', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming']
Category Two: States: ['Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey', 'New Mexico', 'New York', 'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee', 'Texas']

In [7]:
census.set_index(["STNAME", "CTYNAME"], inplace = True)

In [11]:
census.loc["Alabama", :]

,SUMLEV,REGION,DIVISION,STATE,COUNTY,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,POPESTIMATE2011,POPESTIMATE2012,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
CTYNAME,,,,,,,,,,,,,,,,,,,,,
Alabama,40,3,6,1,0,4779736,4780127,4785161,4801108,4816089,...,0.002295,-0.193196,0.381066,0.582002,-0.467369,1.030015,0.826644,1.383282,1.724718,0.712594
Autauga County,50,3,6,1,1,54571,54571,54660,55253,55175,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333
Baldwin County,50,3,6,1,3,182265,182265,183193,186659,190396,...,14.832960,17.647293,21.845705,19.243287,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499
Barbour County,50,3,6,1,5,27457,27457,27341,27226,27159,...,-4.728132,-2.500690,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299
Bibb County,50,3,6,1,7,22915,22919,22861,22733,22642,...,-5.527043,-5.068871,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Tuscaloosa County,50,3,6,1,125,194656,194653,194977,196638,198543,...,3.983504,4.256278,5.261075,4.787490,1.884402,5.306232,5.202679,6.333332,6.057539,3.158710
Walker County,50,3,6,1,127,67023,67023,67004,66641,66184,...,-4.579296,-4.336533,-0.666096,-3.300481,-3.087245,-4.085450,-3.869753,-0.181663,-2.692097,-2.460626
Washington County,50,3,6,1,129,17581,17583,17610,17336,17115,...,-14.708407,-13.062030,-11.181733,1.067236,-0.950486,-13.849940,-12.075121,-10.122411,2.193763,0.118811
Wilcox County,50,3,6,1,131,11670,11665,11557,11488,11365,...,-7.029724,-10.239356,-12.314507,-13.835235,0.090453,-7.029724,-10.239356,-12.314507,-13.835235,0.090453
Winston County,50,3,6,1,133,24484,24483,24401,24340,24176,...,0.410332,-3.916234,2.441548,1.077609,-6.669724,0.410332,-3.957457,2.400166,1.036162,-6.711409

In [12]:
census.loc[("Alabama", "Autauga County"), :]

C:\Users\Anoban\AppData\Local\Temp\ipykernel_8144\1305535208.py:1: PerformanceWarning: indexing past lexsort depth may impact performance.
  census.loc[("Alabama", "Autauga County"), :]

,,SUMLEV,REGION,DIVISION,STATE,COUNTY,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,POPESTIMATE2011,POPESTIMATE2012,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
STNAME,CTYNAME,,,,,,,,,,,,,,,,,,,,,
Alabama,Autauga County,50,3,6,1,1,54571,54571,54660,55253,55175,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.59227,-2.187333

In [17]:
{state for state, city in census.index}

{'Alabama',
 'Alaska',
 'Arizona',
 'Arkansas',
 'California',
 'Colorado',
 'Connecticut',
 'Delaware',
 'District of Columbia',
 'Florida',
 'Georgia',
 'Hawaii',
 'Idaho',
 'Illinois',
 'Indiana',
 'Iowa',
 'Kansas',
 'Kentucky',
 'Louisiana',
 'Maine',
 'Maryland',
 'Massachusetts',
 'Michigan',
 'Minnesota',
 'Mississippi',
 'Missouri',
 'Montana',
 'Nebraska',
 'Nevada',
 'New Hampshire',
 'New Jersey',
 'New Mexico',
 'New York',
 'North Carolina',
 'North Dakota',
 'Ohio',
 'Oklahoma',
 'Oregon',
 'Pennsylvania',
 'Rhode Island',
 'South Carolina',
 'South Dakota',
 'Tennessee',
 'Texas',
 'Utah',
 'Vermont',
 'Virginia',
 'Washington',
 'West Virginia',
 'Wisconsin',
 'Wyoming'}

In [18]:
state_dataframes = dict()
states = {state for state, city in census.index}

for state in states:
    state_dataframes[state] = census.loc[state, :]

In [19]:
len(state_dataframes)

51

In [22]:
state_dataframes.get("Alabama")

,SUMLEV,REGION,DIVISION,STATE,COUNTY,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,POPESTIMATE2011,POPESTIMATE2012,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
CTYNAME,,,,,,,,,,,,,,,,,,,,,
Alabama,40,3,6,1,0,4779736,4780127,4785161,4801108,4816089,...,0.002295,-0.193196,0.381066,0.582002,-0.467369,1.030015,0.826644,1.383282,1.724718,0.712594
Autauga County,50,3,6,1,1,54571,54571,54660,55253,55175,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333
Baldwin County,50,3,6,1,3,182265,182265,183193,186659,190396,...,14.832960,17.647293,21.845705,19.243287,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499
Barbour County,50,3,6,1,5,27457,27457,27341,27226,27159,...,-4.728132,-2.500690,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299
Bibb County,50,3,6,1,7,22915,22919,22861,22733,22642,...,-5.527043,-5.068871,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Tuscaloosa County,50,3,6,1,125,194656,194653,194977,196638,198543,...,3.983504,4.256278,5.261075,4.787490,1.884402,5.306232,5.202679,6.333332,6.057539,3.158710
Walker County,50,3,6,1,127,67023,67023,67004,66641,66184,...,-4.579296,-4.336533,-0.666096,-3.300481,-3.087245,-4.085450,-3.869753,-0.181663,-2.692097,-2.460626
Washington County,50,3,6,1,129,17581,17583,17610,17336,17115,...,-14.708407,-13.062030,-11.181733,1.067236,-0.950486,-13.849940,-12.075121,-10.122411,2.193763,0.118811
Wilcox County,50,3,6,1,131,11670,11665,11557,11488,11365,...,-7.029724,-10.239356,-12.314507,-13.835235,0.090453,-7.029724,-10.239356,-12.314507,-13.835235,0.090453
Winston County,50,3,6,1,133,24484,24483,24401,24340,24176,...,0.410332,-3.916234,2.441548,1.077609,-6.669724,0.410332,-3.957457,2.400166,1.036162,-6.711409

In [23]:
for state, dframe in state_dataframes.items():
    print(f"There are {dframe.shape[0]} rows in {state}'s DataFrame'")

There are 9 rows in Connecticut's DataFrame'
There are 4 rows in Delaware's DataFrame'
There are 57 rows in Montana's DataFrame'
There are 34 rows in New Mexico's DataFrame'
There are 30 rows in Utah's DataFrame'
There are 65 rows in Louisiana's DataFrame'
There are 68 rows in Alabama's DataFrame'
There are 100 rows in Iowa's DataFrame'
There are 88 rows in Minnesota's DataFrame'
There are 63 rows in New York's DataFrame'
There are 11 rows in New Hampshire's DataFrame'
There are 54 rows in North Dakota's DataFrame'
There are 78 rows in Oklahoma's DataFrame'
There are 6 rows in Hawaii's DataFrame'
There are 45 rows in Idaho's DataFrame'
There are 94 rows in Nebraska's DataFrame'
There are 101 rows in North Carolina's DataFrame'
There are 68 rows in Pennsylvania's DataFrame'
There are 40 rows in Washington's DataFrame'
There are 103 rows in Illinois's DataFrame'
There are 67 rows in South Dakota's DataFrame'
There are 15 rows in Vermont's DataFrame'
There are 121 rows in Kentucky's DataFrame'
There are 2 rows in District of Columbia's DataFrame'
There are 47 rows in South Carolina's DataFrame'
There are 83 rows in Mississippi's DataFrame'
There are 76 rows in Arkansas's DataFrame'
There are 56 rows in West Virginia's DataFrame'
There are 59 rows in California's DataFrame'
There are 22 rows in New Jersey's DataFrame'
There are 134 rows in Virginia's DataFrame'
There are 16 rows in Arizona's DataFrame'
There are 84 rows in Michigan's DataFrame'
There are 89 rows in Ohio's DataFrame'
There are 17 rows in Maine's DataFrame'
There are 73 rows in Wisconsin's DataFrame'
There are 93 rows in Indiana's DataFrame'
There are 255 rows in Texas's DataFrame'
There are 160 rows in Georgia's DataFrame'
There are 24 rows in Wyoming's DataFrame'
There are 6 rows in Rhode Island's DataFrame'
There are 106 rows in Kansas's DataFrame'
There are 96 rows in Tennessee's DataFrame'
There are 30 rows in Alaska's DataFrame'
There are 116 rows in Missouri's DataFrame'
There are 65 rows in Colorado's DataFrame'
There are 18 rows in Nevada's DataFrame'
There are 25 rows in Maryland's DataFrame'
There are 68 rows in Florida's DataFrame'
There are 15 rows in Massachusetts's DataFrame'
There are 37 rows in Oregon's DataFrame'

In [24]:
# here we are interested in two columns: the cancellation_policy & review_scores_value

airbnb = pd.read_csv(r"D:/Introduction-to-Data-Science-in-Python/week-3/datasets/listings.csv")
airbnb.head()

,id,listing_url,scrape_id,last_scraped,name,summary,space,description,experiences_offered,neighborhood_overview,...,review_scores_value,requires_license,license,jurisdiction_names,instant_bookable,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,reviews_per_month
0,12147973,https://www.airbnb.com/rooms/12147973,20160906204935,2016-09-07,Sunny Bungalow in the City,"Cozy, sunny, family home. Master bedroom high...",The house has an open and cozy feel at the sam...,"Cozy, sunny, family home. Master bedroom high...",none,"Roslindale is quiet, convenient and friendly. ...",...,NaN,f,NaN,NaN,f,moderate,f,f,1,NaN
1,3075044,https://www.airbnb.com/rooms/3075044,20160906204935,2016-09-07,Charming room in pet friendly apt,Charming and quiet room in a second floor 1910...,Small but cozy and quite room with a full size...,Charming and quiet room in a second floor 1910...,none,"The room is in Roslindale, a diverse and prima...",...,9.0,f,NaN,NaN,t,moderate,f,f,1,1.30
2,6976,https://www.airbnb.com/rooms/6976,20160906204935,2016-09-07,Mexican Folk Art Haven in Boston,"Come stay with a friendly, middle-aged guy in ...","Come stay with a friendly, middle-aged guy in ...","Come stay with a friendly, middle-aged guy in ...",none,The LOCATION: Roslindale is a safe and diverse...,...,10.0,f,NaN,NaN,f,moderate,t,f,1,0.47
3,1436513,https://www.airbnb.com/rooms/1436513,20160906204935,2016-09-07,Spacious Sunny Bedroom Suite in Historic Home,Come experience the comforts of home away from...,Most places you find in Boston are small howev...,Come experience the comforts of home away from...,none,Roslindale is a lovely little neighborhood loc...,...,10.0,f,NaN,NaN,f,moderate,f,f,1,1.00
4,7651065,https://www.airbnb.com/rooms/7651065,20160906204935,2016-09-07,Come Home to Boston,"My comfy, clean and relaxing home is one block...","Clean, attractive, private room, one block fro...","My comfy, clean and relaxing home is one block...",none,"I love the proximity to downtown, the neighbor...",...,10.0,f,NaN,NaN,f,flexible,f,f,1,2.25

In [26]:
airbnb.loc[:, ["cancellation_policy", "review_scores_value"]]

     cancellation_policy  review_scores_value
0               moderate                  NaN
1               moderate                  9.0
2               moderate                 10.0
3               moderate                 10.0
4               flexible                 10.0
...                  ...                  ...
3580              strict                  9.0
3581              strict                  NaN
3582            flexible                  NaN
3583              strict                  7.0
3584            flexible                  NaN

[3585 rows x 2 columns]

In [35]:
# group by the first alphabet of the state

groups = dict()

for group, dframe in census.groupby(lambda multiindex: multiindex[0][0]):
    groups[group] = dframe

In [36]:
groups.keys()

dict_keys(['A', 'C', 'D', 'F', 'G', 'H', 'I', 'K', 'L', 'M', 'N', 'O', 'P', 'R', 'S', 'T', 'U', 'V', 'W'])

In [41]:
for alphabet in groups.keys():
    print("{}: {}".format(alphabet, {state for state, _ in groups.get(alphabet).index}))

A: {'Alabama', 'Arkansas', 'Arizona', 'Alaska'}
C: {'Connecticut', 'California', 'Colorado'}
D: {'Delaware', 'District of Columbia'}
F: {'Florida'}
G: {'Georgia'}
H: {'Hawaii'}
I: {'Illinois', 'Iowa', 'Idaho', 'Indiana'}
K: {'Kansas', 'Kentucky'}
L: {'Louisiana'}
M: {'Montana', 'Minnesota', 'Missouri', 'Michigan', 'Mississippi', 'Maine', 'Maryland', 'Massachusetts'}
N: {'New Mexico', 'New Jersey', 'New York', 'North Carolina', 'North Dakota', 'Nevada', 'New Hampshire', 'Nebraska'}
O: {'Oklahoma', 'Oregon', 'Ohio'}
P: {'Pennsylvania'}
R: {'Rhode Island'}
S: {'South Dakota', 'South Carolina'}
T: {'Tennessee', 'Texas'}
U: {'Utah'}
V: {'Virginia', 'Vermont'}
W: {'Washington', 'Wisconsin', 'Wyoming', 'West Virginia'}

In [47]:
airbnb.groupby("cancellation_policy").agg({"review_scores_value": np.mean})

                     review_scores_value
cancellation_policy
flexible                        9.237421
moderate                        9.307398
strict                          9.081441
super_strict_30                 8.537313

In [48]:
airbnb.groupby("cancellation_policy").agg({"review_scores_value": np.average})

                     review_scores_value
cancellation_policy
flexible                             NaN
moderate                             NaN
strict                               NaN
super_strict_30                      NaN